import { LegalPage } from "@/components/landing/legal-page";

export const metadata = {
  title: "Terms of Service — Obsidia",
  description: "The agreement between you and Obsidia for using the platform.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="May 3, 2026">
      <p>
        These terms govern your use of Obsidia. By creating an account or using
        the service, you agree to them. If you don't, don't use the service.
      </p>

      <h2>1. The service</h2>
      <p>
        Obsidia is a backtesting + alerting platform for crypto traders. We
        provide strategy authoring tools, historical OHLCV data, AI-generated
        market briefs, and optional execution integrations. We are <strong>not</strong> a
        broker, exchange, custodian, or financial advisor. We do not hold your
        funds.
      </p>

      <h2>2. Eligibility</h2>
      <ul>
        <li>You must be at least 18 years old.</li>
        <li>You must not be on any sanctioned-persons list (OFAC, UN, EU).</li>
        <li>You're responsible for compliance with your local laws regarding crypto trading.</li>
      </ul>

      <h2>3. Your account</h2>
      <p>
        You sign in via Google OAuth (Supabase Auth). You're responsible for
        keeping your session secure. Notify us immediately of any unauthorized
        access.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You may not:</p>
      <ul>
        <li>Use the service to manipulate markets, coordinate pump-and-dumps, or run wash-trading schemes.</li>
        <li>Reverse-engineer, scrape, or attempt to extract proprietary content (e.g. private creator strategies).</li>
        <li>Resell access to your account, or share API keys with parties who haven't agreed to these terms.</li>
        <li>Attack our infrastructure (DDoS, fuzzing without disclosure).</li>
      </ul>

      <h2>5. Subscriptions &amp; billing</h2>
      <ul>
        <li>Pricing is published on our pricing page. Charges are monthly via Stripe.</li>
        <li>Cancel any time. No refunds for partial months unless required by law.</li>
        <li>We may change prices with 30 days notice; existing subscribers keep current price for the remainder of their term.</li>
        <li>Marketplace strategies: 70% of subscription revenue goes to the creator; 30% to Obsidia for hosting + payment processing.</li>
      </ul>

      <h2>6. Strategies and intellectual property</h2>
      <ul>
        <li>You retain ownership of strategies you author. By publishing to the marketplace, you grant Obsidia a non-exclusive license to host and display them.</li>
        <li>Subscribing to a marketplace strategy gives you access to its <em>signals</em>, not its underlying logic.</li>
        <li>You agree not to redistribute signals you receive to non-subscribers.</li>
      </ul>

      <h2>7. AI-generated briefs</h2>
      <p>
        AI briefs are generated by Anthropic Claude based on the data we feed
        it. They are educational synthesis, not financial advice. We don't
        guarantee accuracy. The model can be wrong. Use your own judgment.
      </p>

      <h2>8. Risk disclosure</h2>
      <p>
        Trading crypto involves substantial risk including total loss of capital.
        Past backtest performance does not guarantee future results. No strategy
        on Obsidia — verified or not — guarantees profit. See our full <a href="/disclaimer">risk
        disclosure</a> for the long version.
      </p>

      <h2>9. Service availability</h2>
      <p>
        We aim for 99.5% uptime but make no guarantee. Backtests may be
        unavailable during data-pipeline maintenance. Live alerts may be
        delayed during exchange outages. Status: <a href="/status">obsidia.fi/status</a>.
      </p>

      <h2>10. Liability</h2>
      <p>
        To the maximum extent permitted by law, Obsidia's aggregate liability is
        limited to the amount you paid us in the 12 months before the claim,
        or $100, whichever is greater. We are not liable for trading losses,
        missed opportunities, or third-party API failures.
      </p>

      <h2>11. Termination</h2>
      <p>
        Either party may terminate the agreement at any time. We may suspend
        accounts that violate these terms or engage in fraud. Upon termination,
        we delete your data per our privacy policy.
      </p>

      <h2>12. Governing law</h2>
      <p>
        These terms are governed by the laws of Singapore (or the applicable
        jurisdiction of Obsidia's incorporated entity at the time). Disputes
        resolved by binding arbitration in that jurisdiction.
      </p>

      <h2>13. Changes</h2>
      <p>
        Material changes are emailed to you 14 days before taking effect.
        Continued use after the effective date constitutes acceptance.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions? <a href="mailto:legal@obsidia.fi">legal@obsidia.fi</a>.
      </p>
    </LegalPage>
  );
}
